Feat/profile screens
mfajarhafidh/Food-Delivery pull request #2
Opened 2023-02-23 10:53 UTC by mfajarhafidh

## Profile Screen
![image](https://user-images.githubusercontent.com/94110628/220866563-a3eeacb3-e8e3-4d1b-8932-73e39750b330.png)

## Profile Change Screen
![image](https://user-images.githubusercontent.com/94110628/220874320-44cf8a67-7be7-4b63-98fb-a046106e67aa.png)

## Shrink SlideMenu Drawer Screen
![image](https://user-images.githubusercontent.com/94110628/220945693-d774bbd1-b499-4885-a3e0-cb3aee5c49d9.png)

2023-02-24 09:08 UTC, baguskto commented on lib/pages/drawer/shrink_drawer_screen.dart
> +  @override
test

2023-02-24 09:08 UTC, baguskto requested changes

2023-02-24 09:08 UTC, baguskto commented on README.md
> +![image](https://user-images.githubusercontent.com/94110628/220866563-a3eeacb3-e8e3-4d1b-8932-73e39750b330.png)
hahaa

2023-02-27 06:43 UTC, raiszidane95 requested changes
Kalo bisa icons nya jangan dari image assets. pake icons bawaan dari flutter atau dependency aja

2023-02-27 07:02 UTC, dadahtaufikpermana commented on lib/pages/drawer/shrink_drawer_screen.dart
> +                      const Text("Sign-Out",
jika menyesuaikan dengan figma, huruf "o" nya kecil

2023-02-27 07:08 UTC, alghanykennedy commented
mas fajar, saran / masukkan untuk memudahkan dan menyamakan tema warna apps baiknya memuat folder tersendiri untuk color_scheme fungsinya sama seprti reusable button jadi tidak perlu menghfal kode hexnya.

2023-02-27 07:09 UTC, alghanykennedy commented
klo mau pinjem / pakai screen home untuk tampilan shrink side menu boleh banget mampir ke home_screen saya dan jangan lupa tinggalkan comment yaa!

2023-02-27 07:24 UTC, mfajarhafidh commented
> Kalo bisa icons nya jangan dari image assets. pake icons bawaan dari flutter atau dependency aja

maaf mas kalo slicing layout, usahain pake yang ada di figmanya aja, karna kan tinggal copy paste aja

2023-02-27 07:26 UTC, mfajarhafidh commented on lib/pages/drawer/shrink_drawer_screen.dart
> +                      const Text("Sign-Out",
oke sudah kuganti ya
https://github.com/mfajarhafidh/Food-Delivery/pull/2/commits/32129a3662c488d9e82af2abb1f15354a8a1be52

2023-02-27 07:29 UTC, dadahtaufikpermana commented on lib/pages/drawer/shrink_drawer_screen.dart
> +                      const Text("Sign-Out",
oke mantap

2023-02-27 07:49 UTC, Daffayy commented on lib/pages/profile/profile_change_screen.dart
> +      resizeToAvoidBottomInset: false,
ini fungsinya untuk apa ka?

2023-02-27 08:00 UTC, mfajarhafidh commented on lib/pages/profile/profile_change_screen.dart
> +      resizeToAvoidBottomInset: false,
SafeArea itu tujuannya agar auto-padding kalo hape nya bernotch, sama ga terlalu bawah banget kalo naro widget. Jadi tetep di area "Safe" nya.
resizeToAvoidBottomInset itu gunanya kalo ngeluarin keyboard, widget2nya ga kelempar ke atas

2023-02-27 08:13 UTC, raiszidane95 approved these changes
Nice. LGTM!

2023-02-27 08:13 UTC, baguskto approved these changes

2023-02-27 08:14 UTC, mfajarhafidh commented
> mas fajar, saran / masukkan untuk memudahkan dan menyamakan tema warna apps baiknya memuat folder tersendiri untuk color_scheme fungsinya sama seprti reusable button jadi tidak perlu menghfal kode hexnya.

Oke mas nanti kedepannya ku buat class Style buat color nya

2023-02-27 08:15 UTC, merged